spring:
  application:
    name: students
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3307/ensa?createDatabaseIfNotExist=true
    username: root
    password: root
  hikari:
    connection-test-query: SELECT 1
    minimum-idle: 5
    maximum-pool-size: 10
    idle-timeout: 30000
    pool-name: HikariCP

